### ISSUE TITLE
Generated verifier length

### ISSUE THREAD

**Issue by Windvis** [BitySA/oauth2-auth-code-pkce#1]
Hi there!

We're experimenting with the "new" OAuth2 Auth code + PKCE flow in SPA apps with different OAuth SaaS providers. We noticed that Okta was giving verification errors. After inspecting, it seems that the verifiers generated by this library are longer than the max length of 128 characters (.length returns 171). Limiting the generated verifier to the the max length did fix the error we were getting.

I'm not 100% sure what the cause of this is since I'm not super familiar with this kind of code, but maybe the [Okta library](https://github.com/okta/okta-auth-js/blob/fb9a7c6ca9f8f8d4a9a9fa14be99a7dbca5f1ec3/packages/okta-auth-js/lib/pkce.js#L36) or this [PKCE verifier + challenge generator library](https://github.com/lonnelars/verifier-and-challenge) might provide more insights. My guess is that [`btoa`](https://github.com/BitySA/oauth2-auth-code-pkce/blob/19b223652799a32a8f0252fd9578ff54490817a0/index.ts#L428) might have something to do with it 😄 .

**Comment by lf94** [comment]
Interesting, I'll take a look. Thank you for all your bug reports @Windvis and sorry I am just seeing them now.

**Comment by lf94** [comment]
For what it's worth, I did hardcode the length to be the maximum length: https://github.com/BitySA/oauth2-auth-code-pkce/blob/master/index.ts#L151

It's also possible that the verifier is incorrectly checking. We used ORY Hydra for our tests and everything works as expected, as per the RFCs.

**Comment by lf94** [comment]
@Windvis another issue is, a lot of these libs will use base64 encoding **which is not correct**. It must specifically be base64 url encoding which is **not** the same as regular base64 encoding.

**Comment by lf94** [comment]
@Windvis ok, a quick shot at what the issue may be.

As per the RFC https://tools.ietf.org/html/rfc7636#section-4.1 , the code-verifier generated must be between 43 and 128 characters.

In our code, this behavior is encoded [here](https://github.com/BitySA/oauth2-auth-code-pkce/blob/master/index.ts#L535):

```ts
    const output = new Uint32Array(RECOMMENDED_CODE_VERIFIER_LENGTH);
    crypto.getRandomValues(output);
    const codeVerifier = OAuth2AuthCodePKCE.base64urlEncode(Array
      .from(output)
      .map((num: number) => PKCE_CHARSET[num % PKCE_CHARSET.length])
      .join(''));
```

So we create a 128 length array to be filled with random numbers, then we fill the array with PKCE character set characters.

At this point, we `base64urlEncode` the array, which is what is probably causing the 171 characters.

The note in the RFC says that the length after encoding a **32** byte sequence should be 43. So I guess here, the `RECOMMENDED_CODE_VERIFIER_LENGTH` should be reduced to a number that when `base64urlEncoded`, outputs a value of length 128.

**Comment by lf94** [comment]
@Windvis please try this again when you have time. A new version (2.3.0) will have been published.

**Comment by lf94** [comment]
Just doing some more investigation into what the other implementations are doing.

----

The [Okta implementation](https://github.com/okta/okta-auth-js/blob/fb9a7c6ca9f8f8d4a9a9fa14be99a7dbca5f1ec3/packages/okta-auth-js/lib/pkce.js#L36) is trying to be clever (why, I have no clue), and using at the minimum 22 bytes, and then expanding this to 44 characters by converting them from decimal into hex, and then truncating by the length or by 128.

This means the Okta implementation **is not using the full PKCE character set**, which means it is substantially weaker than implementations that do use it or a large subset (as seen below).

----

[Lars's implementation](https://github.com/lonnelars/verifier-and-challenge/blob/master/index.js) seems to just fill a buffer and directly base64 url encode it, which is actually much better, since essentially they are using a subset of the PKCE character set. The reality is they are missing out on 2 characters, `.` and `~`, but I think that has minimal if any effect.

Unfortunately they have gone with the smallest verifier length: 32/43.

**Comment by Windvis** [comment]
Thanks for the information. That was very insightful!

I'll get back to you when we tested the new version!

**Comment by lf94** [comment]
I tested this myself in the other issue (https://github.com/BitySA/oauth2-auth-code-pkce/issues/2) and confirmed it works. I will close. :slightly_smiling_face:
