### ISSUE TITLE
Support Cookie Storage and/or Session Storage

### ISSUE THREAD

**Issue by ispyinternet** [BitySA/oauth2-auth-code-pkce#8]
Local Storage is only really suitable in very secure environments as the tokens will persist even after a browser has been closed.

SessionStorage and Cookie Storage provide better backend choices for applications that intend to be deployed to less secure environments.

Would you consider providing a config option to allow the consumer to select which storage backend is used?

You could include this library:

https://github.com/jherax/proxy-storage

or simply use it for inspiration if you wanted to keep this library as lean as it currently is.

**Comment by lf94** [comment]
What you're suggesting is kind of odd to me. All access tokens are required to have an expiry time of some sort (at first I thought that maybe there *is* a session-based time thing, but no). See https://tools.ietf.org/html/rfc6749#section-4.2.2 :

>    expires_in
>          RECOMMENDED.  The lifetime in seconds of the access token.  For
>          example, the value "3600" denotes that the access token will
>          expire in one hour from the time the response was generated.
>          If omitted, the authorization server SHOULD provide the
>          expiration time via other means or document the default value.

So even though they persist, if the expiry time is up, then the token is invalid. I also feel that intuitively, the whole point behind a token system is so people don't have to constantly re-login. Otherwise we would just continue to use cookie-based sessions...At least that's what I think.

I suggest if you require this custom behavior, to fork this repository and change out the storage. :slightly_smiling_face:
